# Generated by Django 4.2.6 on 2023-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODOList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('task', models.TextField(max_length=1000)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(max_length=50)),
            ],
        ),
    ]
