# Generated by Django 4.2.6 on 2023-10-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_app', '0002_alter_todolist_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='task',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
